### ISSUE TITLE
linux-aarch64 files missing for 1.5.1-1, which breaks setup-micromamba on linux-aarch64

### ISSUE THREAD

**Issue by dan-blanchard** [mamba-org/micromamba-releases#17]
We recently started having build failures after 1.5.1-1 was released because we use https://github.com/mamba-org/setup-micromamba with version set to the default `latest` and linux-aarch64 runners. The errors are 404s like:

```
Install micromamba
  Error: Error installing micromamba: Unexpected HTTP response: 404
Error: Unexpected HTTP response: 404
```

They seem to be caused by there being no linux-aarch64 files in the [1.5.1-1 assets list](https://github.com/mamba-org/micromamba-releases/releases/tag/1.5.1-1). Could you please add the linux-aarch64 files to the release?

**Comment by pavelzw** [comment]
This is because the aarch64 in https://github.com/conda-forge/micromamba-feedstock build failed. CC @AntoinePrv

I clicked on rerun now.

I think it makes sense to only publish a new release here once all builds are finished. If not all builds are available on anaconda.org, the automatic release should create an issue here.

**Comment by pavelzw** [comment]
Fixed now, thanks for the issue @dan-blanchard

**Comment by dan-blanchard** [comment]
Thanks for fixing!
